server:
  port: 80

dubbo:
  application:
    # 应用名称
    name: dubbo-web
  registry:
    # zookeeper地址
    address: zookeeper://127.0.0.1:2181
  # 注册服务采用的协议 端口号
  protocol:
    name: dubbo
    port: 20880